import React from 'react';
import { FileText, Brain, TrendingUp, Users, MessageSquare } from 'lucide-react';

function AIReport({ report }) {
  if (!report) {
    return (
      <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-indigo-100 rounded-lg">
            <Brain className="w-6 h-6 text-indigo-600" />
          </div>
          <h3 className="text-xl font-bold text-gray-900">AI Analysis Report</h3>
        </div>
        <div className="text-center py-8">
          <p className="text-gray-500">No analysis report available</p>
        </div>
      </div>
    );
  }

  const formatReport = (text) => {
    const sections = text.split('\n\n');
    return sections.map((section, index) => {
      if (section.includes('REPORT') || section.includes('ANALYSIS')) {
        return (
          <div key={index} className="mb-6">
            <h4 className="text-lg font-bold text-gray-900 mb-3 flex items-center gap-2">
              <FileText className="w-5 h-5 text-indigo-600" />
              {section.trim()}
            </h4>
          </div>
        );
      }
      
      if (section.includes('Recommendations:') || section.includes('Key findings:')) {
        const lines = section.split('\n');
        const title = lines[0];
        const items = lines.slice(1).filter(line => line.trim());
        
        return (
          <div key={index} className="mb-6">
            <h5 className="font-semibold text-gray-800 mb-3 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-green-600" />
              {title}
            </h5>
            <ul className="space-y-2">
              {items.map((item, itemIndex) => (
                <li key={itemIndex} className="flex items-start gap-2">
                  <span className="w-2 h-2 bg-indigo-500 rounded-full mt-2 flex-shrink-0"></span>
                  <span className="text-gray-700">{item.replace(/^\d+\.\s*/, '')}</span>
                </li>
              ))}
            </ul>
          </div>
        );
      }
      
      return (
        <p key={index} className="text-gray-700 leading-relaxed mb-4">
          {section.trim()}
        </p>
      );
    });
  };

  return (
    <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-indigo-100 rounded-lg">
          <Brain className="w-6 h-6 text-indigo-600" />
        </div>
        <h3 className="text-xl font-bold text-gray-900">AI Analysis Report</h3>
      </div>
      
      <div className="bg-gradient-to-r from-indigo-50 to-purple-50 rounded-lg p-6 border border-indigo-200">
        <div className="prose max-w-none">
          {formatReport(report)}
        </div>
        
        <div className="mt-6 pt-4 border-t border-indigo-200">
          <div className="flex items-center gap-2 text-sm text-indigo-600">
            <Brain className="w-4 h-4" />
            <span className="font-medium">Generated by AI Analysis Engine</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AIReport;